version: '3.8'

services:
  postgres_keycloak:
    image: postgres:14.2
    command: postgres -c 'max_connections=200'
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: kc
      POSTGRES_PASSWORD: 1234
    healthcheck:
      test: "exit 0"
    networks:
      - ql-networks
    volumes:
      - postgres-kc-data:/var/lib/postgresql/data

  keycloak-ql:
    container_name: keycloak-provider
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - "8080:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_keycloak
      KC_DB_URL_DATABASE: keycloak
      KC_DB_PASSWORD: 1234
      KC_DB_USERNAME: kc
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: root
      KEYCLOAK_ADMIN_PASSWORD: 1234
    command: ["start-dev", "--import-realm"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/realms/quiz-tech"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      postgres_keycloak:
        condition: service_healthy
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data
    networks:
      - ql-networks

  mongodb-category:
    container_name: category-mongodb
    image: mongo
    ports:
      - "27018:27017"
    expose:
      - "27018"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ixml
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - mongo-category-data:/data/db
    networks:
      - ql-networks

  mongo-express:
    container_name: mongo-express-ms
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ixml
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_SERVER: mongodb-category
      ME_CONFIG_BASICAUTH_USERNAME: ixml
      ME_CONFIG_BASICAUTH_PASSWORD: 1234
    networks:
      - ql-networks

  config-server:
    build: ./services/config-server
    container_name: config-server
    ports:
      - "8000:8000"
    restart: always
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/actuator/health"]
      interval: 20s
    networks:
      - ql-networks

  discovery:
    build: ./services/discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    expose:
      - "8761"
    environment:
      URL_CONFIG_SERVER: http://config-server:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 20s
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - ql-networks

  gateway-service:
    container_name: gateway-service
    build: ./services/gateway-service
    ports:
      - "8200:8200"
    environment:
      CONFIG_SERVER_URL: http://config-server:8000
      DISCOVERY_SERVER_URL: http://root_fuji:1234@discovery:8761/eureka/
      KEYCLOAK_ISSUER_URI: http://keycloak-ql:8080/realms/q-learning-realm
      KEYCLOAK_KEY_URL: http://keycloak-ql:8080/realms/quiz-tech/protocol/openid-connect/certs
    depends_on:
      - config-server
      - discovery
      - keycloak-ql
    networks:
      - ql-networks

  quiz-service:
    container_name: quiz-service-ms
    build: ./services/quiz-service
    env_file: ./.env
    ports:
      - "6110:6110"
    environment:
      SPRING_APPLICATION_JSON: '{
                "spring.data.mongodb.uri" : "mongodb://$MONGODB_USER:$MONGODB_PASSWORD@mongodb-category:$MONGODB_DOCKER_PORT/$MONGODB_DATABASE?authSource=admin"
              }'
      CONFIG_SERVER_URL: http://config-server:8000
      DISCOVERY_SERVER_URL: http://root_fuji:1234@discovery:8761/eureka/
      KEYCLOAK_ISSUER_URI: http://keycloak-ql:8080/realms/q-learning-realm
      KEYCLOAK_KEY_URL: http://keycloak-ql:8080/realms/q-learning-realm/protocol/openid-connect/certs
    depends_on:
      - keycloak-ql
      - discovery
      - mongodb-category
    networks:
      - ql-networks

  category-service:
    container_name: category-service-ms
    build: ./services/category-service
    env_file: ./.env
    ports:
      - "6100:6100"
    expose:
      - "6100"
    environment:
      SPRING_APPLICATION_JSON: '{
                "spring.data.mongodb.uri" : "mongodb://$MONGODB_USER:$MONGODB_PASSWORD@mongodb-category:$MONGODB_DOCKER_PORT/$MONGODB_DATABASE?authSource=admin"
              }'
      CONFIG_SERVER_URL: http://config-server:8000
      DISCOVERY_SERVER_URL: http://root_fuji:1234@discovery:8761/eureka/
      KEYCLOAK_ISSUER_URI: http://keycloak-ql:8080/realms/q-learning-realm
      KEYCLOAK_KEY_URL: http://keycloak-ql:8080/realms/q-learning-realm/protocol/openid-connect/certs
    depends_on:
      - keycloak-ql
      - discovery
      - mongodb-category
    networks:
      - ql-networks

networks:
  ql-networks:
    driver: bridge

volumes:
  mongo-quiz-data:
  mongo-category-data:
  keycloak_data:
  postgres-kc-data:
