version: '3.8'

services:
  keycloak:
    container_name: keycloak-provider
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: ixml
      KEYCLOAK_ADMIN_PASSWORD: 1234
    command:
      - "start-dev"
    networks:
      - ql-networks


  mongodb:
    container_name: quiz-mongodb
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ixml
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - mongo-quiz-data:/data/db
    networks:
      - ql-networks

  mongo-express:
    container_name: mongo-express-ms
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ixml
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: ixml
      ME_CONFIG_BASICAUTH_PASSWORD: 1234
    networks:
      - ql-networks

  discovery:
    build: ./services/discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    expose:
      - "8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 15s
    networks:
      - ql-networks

networks:
  ql-networks:

volumes:
  mongo-quiz-data:
  mongo-category-data:
